# Generated by Django 2.2.2 on 2019-06-05 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='title',
        ),
    ]
