# Generated by Django 2.2.2 on 2019-06-13 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20190613_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chat',
            new_name='conversation',
        ),
    ]
